version: '2'

services:
  db:
    container_name: testhive-postgres
    restart: always
    image: postgres:latest
    volumes:
      - "database-app:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  web:
    container_name: testhive-app
    build: .
    command: bash -c "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    depends_on:
      - db

volumes:
  database-app:


